Fix: docker file outside backend

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -1,48 +1,76 @@
-name: Fitness Tracker CI/CD
-run-name: BUILD-SCAN
+# name: Fitness Tracker CI/CD
+# run-name: BUILD-SCAN
+# on:
+#   push:
+#     branches: [ "master" ]
+
+# jobs:
+#   build:
+#     name: CI - Build & Push Docker Image
+#     runs-on: ubuntu-latest
+
+#     steps:
+#     - name: Checkout Code
+#       uses: actions/checkout@v4
+
+#     - name: Setup Node.js
+#       uses: actions/setup-node@v4
+#       with:
+#         node-version: 18
+
+#     - name: Install Dependencies
+#       run: npm install
+
+#     - name: Run Tests
+#       run: npm test || true
+
+#     - name: Install Docker
+#       uses: docker/setup-buildx-action@v3
+
+#     - name: Login to Docker Hub
+#       uses: docker/login-action@v3
+#       with:
+#         username: ${{ secrets.DOCKER_USERNAME }}
+#         password: ${{ secrets.DOCKER_PASSWORD }}
+
+#     - name: Build Docker Image
+#       run: docker build -t "${{ secrets.DOCKER_USERNAME }}"/fitness-tracker:latest .
+
+#     - name: Trivy install
+#       run: |
+#         sudo apt update 
+#         sudo apt install trivy -y
+    
+#     - name: Trivy scan
+#       run: trivy image --severity HIGH,CRITICAL ${{ secrets.DOCKER_USERNAME }}/fitness-tracker:latest
+
+#     - name: Push Docker Image
+#       run: docker push ${{ secrets.DOCKER_USERNAME }}/fitness-tracker:latest
+
+name: Build
+
 on:
   push:
-    branches: [ "master" ]
+    branches:
+      - master
+
 
 jobs:
   build:
-    name: CI - Build & Push Docker Image
+    name: Build and analyze
     runs-on: ubuntu-latest
-
-    steps:
-    - name: Checkout Code
-      uses: actions/checkout@v4
-
-    - name: Setup Node.js
-      uses: actions/setup-node@v4
-      with:
-        node-version: 18
-
-    - name: Install Dependencies
-      run: npm install
-
-    - name: Run Tests
-      run: npm test || true
-
-    - name: Install Docker
-      uses: docker/setup-buildx-action@v3
-
-    - name: Login to Docker Hub
-      uses: docker/login-action@v3
-      with:
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
-
-    - name: Build Docker Image
-      run: docker build -t "${{ secrets.DOCKER_USERNAME }}"/fitness-tracker:latest .
-
-    - name: Trivy install
-      run: |
-        sudo apt update 
-        sudo apt install trivy -y
     
-    - name: Trivy scan
-      run: trivy image --severity HIGH,CRITICAL ${{ secrets.DOCKER_USERNAME }}/fitness-tracker:latest
-
-    - name: Push Docker Image
-      run: docker push ${{ secrets.DOCKER_USERNAME }}/fitness-tracker:latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+      - uses: SonarSource/sonarqube-scan-action@v6
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+      # If you wish to fail your job when the Quality Gate is red, uncomment the
+      # following lines. This would typically be used to fail a deployment.
+      # - uses: SonarSource/sonarqube-quality-gate-action@v1
+      #   timeout-minutes: 5
+      #   env:
+      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
